default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: db
  username: <%= ENV['DB_ENV_POSTGRES_USER'] %>
  password: <%= ENV['DB_ENV_POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: docker-rails-blog_development

test:
  <<: *default
  database: docker-rails-blog_test

production: &production
  <<: *default
  host:     <%= ENV['POSTGRESQL_ADDRESS'] %>
  database: <%= ENV['POSTGRESQL_DATABASE'] %>
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
