default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: docker-rails-blog_development
  username: <%= ENV['DB_ENV_POSTGRES_USER'] %>
  password: <%= ENV['DB_ENV_POSTGRES_PASSWORD'] %>
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] %>

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production: &production
  <<: *default
  host:     <%= ENV['POSTGRESQL_ADDRESS'] %>
  database: <%= ENV['POSTGRESQL_DATABASE'] %>
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
